### ISSUE TITLE
List of ToDos

### ISSUE THREAD

**Issue by kmmraj** [GeoThings/ReKotlin#1]
First of all, many thanks for the porting. Looks very interesting.
I want to contribute, to avoid the duplicate work, could you please list the todos in the roadmap.

**Comment by ambientlight** [comment]
@kmmraj Thanks a lot. Looking forward to your contribution!

Certainly. Will be done tonight.

**Comment by ambientlight** [comment]
@kmmraj:

The milestone: https://github.com/GeoThings/ReKotlin/milestone/1 containing the issues for our initial roadmap has been added. We can further synchronize inside individual issues there.
